RK2
java-park-mail-ru/Drive-02-2018 pull request #4
Opened 2018-05-05 16:18 UTC by Andreynnt

2018-05-09 16:02 UTC, KSolovyev commented
Полюбому нужно порешать конфликты и добавить CI c checkstyle

2018-05-10 17:03 UTC, Andreynnt commented
Конфликты решены, а чекстайл был подключен

2018-05-10 19:08 UTC, Badya requested changes
Что с трависом?

2018-05-10 19:10 UTC, Andreynnt commented
а что с ним не так? Проверку проходит

2018-05-10 19:14 UTC, Badya requested changes

2018-05-10 19:14 UTC, Badya commented on src/main/java/project/services/UserService.java
> +    //todo транзакции, чтобы бд не херить
Ну и где транзакции?)

2018-05-10 19:14 UTC, Badya commented on src/main/java/project/rowmapper/ApiRowMapper.java
> +public class ApiRowMapper {
Можно перенести мапперы в объект создаваемый, и оттуда пользоваться метод-референсом

2018-05-10 19:15 UTC, Badya commented
@Andreynnt я вот тут хочу видеть интеграцию с трависом прямо в ПРе

2018-05-12 16:30 UTC, Andreynnt commented
Поправил замечания. Транзакции есть там, где они нужны

2018-05-21 13:47 UTC, Badya requested changes

2018-05-21 13:47 UTC, Badya commented on src/main/java/project/services/SingleplayerService.java
> +    public Integer createQuestion(QuestionModel question) {
`@Transactional`?

2018-05-21 13:47 UTC, Badya commented on src/main/java/project/services/SingleplayerService.java
> +    public ArrayList<SetModel> getSet(Integer numberOfQuestions, String theme) {
`List` по интерфейсу и везде ниже

Возможно вообще стоит возвращать Set

2018-05-21 13:47 UTC, Badya commented on src/test/java/project/services/UserServiceTest.java
> +@RunWith(SpringRunner.class)
почему junit4? на лекции говорили про 5

2018-05-24 16:59 UTC, Badya requested changes

2018-05-24 16:59 UTC, Badya commented on src/main/java/project/models/QuestionAndAnswer.java
> +public class QuestionAndAnswer {
Не является ли эта модель избыточной?

2018-05-24 16:59 UTC, Badya commented on src/test/java/project/controllers/UserControllerTest.java
> +public class UserControllerTest {
?

2018-05-24 16:59 UTC, Badya commented on src/test/java/project/services/UserServiceTest.java
> +        this.user = new UserModel("tester@mail.ru","tester", 0, "12345qwerty");
Нужно такое в `@Before` или `@BeforeClass` - использовать конструктор в тесте не очень хорошая практика

2018-05-24 16:59 UTC, Badya commented on src/test/java/project/services/UserServiceTest.java
> +    private void assertDifference(@NotNull UserModel expected, @NotNull UserModel actual) {
Вы можете переопределить `equals` в `UserModel` и использовать `assertEquals`

2018-05-27 12:28 UTC, Andreynnt commented on src/main/java/project/models/QuestionAndAnswer.java
> +public class QuestionAndAnswer {
Мне довольно удобно ее использовать в методе SingleplayerService.getSet(). Метод получился довольно мудреный, но с моей выбранной архитектурой БД по-другому можно только, если делать несколько запросов. А при текущем варианте я делаю всего 1. Поэтому я считаю, что норм

2018-05-30 04:48 UTC, merged