Rk3
java-park-mail-ru/Drive-02-2018 pull request #5
Opened 2018-05-30 05:42 UTC by Andreynnt

Multiplayer done

2018-05-30 09:37 UTC, isopov commented
- В РК3 тоже нужны тесты. Если совсем не можете написать на механику - напишите хотя бы на систему сообщений. В ней сейчас есть странности - `project.mechanics.messages.Start` пересылается же с сервера на клиент, но для него есть какие-то ошметки (неработающие же?) десериализации из json-а - он упоминается в аннотации на `project.websockets.Message` и у его Payload есть JsonCreator.
- Такая комбинация не работает
```
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@Transactional
```
При этом вы в этом тесте вообще напрямую методы контроллера вызываете. То есть вам реальный веб-сервер не нужен.
- testcontainers без scope test, то есть со scope compile - явная ошибка
- в миграциях БД Вы, видимо, вообще не разобрались - на каждой новой базе применяются последовательно все. Поэтому вторую и последующие странно называться "init". И поэтому выполняется `CREATE TABLE IF NOT EXISTS answers` в V2__init.sql, а во всех последующих миграциях создание этой таблицы игнорируется (и у неё, видимо, не хватает колонок). Плохо что из-за этого у вас не падают тесты. Вообще в миграциях `IF NOT EXISTS` применять не надо - нужно делать просто create, а потом alter-ы.
- зачем версию postgresql-драйвера явно определяете, а не пользуетесь унаследованной от spring-boot-starter-parent ?
- `Message` - два класса с одинаковым именем в разных пакетах - не получится какой-то из них переназвать нормально?
- `project.status.StatusCodes` - совсем не на java написано. Почему это enum-ами не заменить всё?
- `@SuppressWarnings` - пересмотрите и удалите ненужные. unused явно ненужный на Message (одном из), OverlyBroadThrowsClause на `project.websockets.GameWebSocketHandler#afterConnectionEstablished` странный сразу по двум причинам - это переопределенный класс и такая инспекция на него не должна реагировать (выбрасывание исключения является частью реализации API), и оттуда throws можно вообще убрать - удалив неиспользуемый с `project.websockets.RemotePointService#registerUser`
- `throw new IOException` - пересмотрите - многое из этого явно не IO, а там где IO, я бы заменил на `UncheckedIOException`
- `project.websockets.MessageSender#send` - странный метод, тем более, что в единственном его вызове возвращаемый результат не используется.
- Немножко рвёт мозг:
```
    @Autowired
    private final ObjectMapper objectMapper;
```
а с учетом того, что final в java несовсем final и спринг туда таки может подставить что-то, я бы это считал не безобидной штукой, а вредной - удалите.
- `@Transactional(rollbackFor = Exception.class)` - зачем?
- Форматирование кода странное
```
   @Transactional(rollbackFor = Exception.class)
    public...
```
java (как и многие другие языки) хороша тем, что можно её форматировать автоформаттером и не заморачиваться.
- `project.models.AnswerModel#correct` - а почему не примитвный boolean?
- `QuestionModel` - тоже очень странное что-то, почему id не примитив? equals/hashcode будут NPE выбрасывать, если там будет null
- `.setAllowedOrigins("*")` - а это точно работает и сессии через вебсокеты есть?

2018-05-30 09:37 UTC, isopov requested changes
Замечание в комментарии.

2018-05-31 08:15 UTC, Andreynnt commented
**По первому пункту:** Start упоминается в project.mechanics.messages.Start, чтобы метод objectMapper.writeValueAsString(startMessage) сериализовал объект правильно, соответствуя договоренности с фронтом. То есть там будет структура {event: "EVENTS_GAME_START", payload: {…}}. Если убрать класс Start из из project.mechanics.messages.Start, то отправляться будет {event: "Start", payload: {…}}. Остальное в этом замечании поправил
**По четвертому пункту**: про миграции. я просто забыл DROP TABLE IF EXISTS tableName в каждой новой миграции, для изменяемых таблиц. Именно это я имел в виду. Можно, конечно, и нужно алтерами приделывать столбцы, но можно и все удалять, а потом заново создавать. Конечно для продакшана это отвратительное решение. Сейчас я просто добавил миграцию V6: в которой удаляю, если есть, а потом создаю табличку. Теперь со столбцами все точно ок, их хватает

2018-05-31 08:30 UTC, isopov commented on src/main/java/project/models/QuestionModel.java
>      @JsonInclude(JsonInclude.Include.NON_NULL)
На примитивном типе теперь смотрится совсем странно))

2018-05-31 08:32 UTC, isopov commented on src/test/java/project/controllers/UserControllerTest.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.MOCK)
А почему не NONE?

2018-05-31 08:32 UTC, isopov commented on src/test/java/project/services/UserServiceTest.java
> +        System.out.println('3');
Пролезают строчки, которые вы не планировали коммитить, видимо ;-)

2018-05-31 08:38 UTC, merged